HReady-Django/HReady/HReady/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views as user_views
from tracking import views as tracking_views

from .views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='landing'),
    path('home/', user_views.home, name='home'),
    path('users/', include('users.urls', namespace='users')),
    path('system/', include('system.urls', namespace='system')),    
    path('charts/', include('charts.urls', namespace='charts')),
    path('tracking/', include('tracking.urls', namespace='tracking'))
]

HReady-Django/HReady/charts/urls.py
from django.shortcuts import redirect, render
from django.urls import path, include

from .views import ChartData, HomeView

app_name = 'charts'

urlpatterns = [
    path('', HomeView.as_view(), name='chart'),
    path('data/', ChartData.as_view(), name='chart-data')
]

HReady-Django/HReady/notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

HReady-Django/HReady/users/urls.py
from django.shortcuts import redirect, render
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', user_views.SignUpView.as_view(), name='signup'),
    path('signup/first_responder', user_views.FirstResponderSignupView.as_view(), name='firstresponder_signup'),
    path('signup/hospital', user_views.HospitalAdminSignupView.as_view(), name='hospitaladmin_signup')
]

HReady-Django/HReady/charts/models.py
from django.db import models

# Create your models here.

HReady-Django/HReady/charts/views.py
from django.shortcuts import render

from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import View

from rest_framework.views import APIView
from rest_framework.response import Response

from system.models import Subjects, HospitalGeneralInfo, Cases

from collections import defaultdict

import pickle

# Create your views here.

class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'charts/charts.html', {"customers": 10})


class ChartData(APIView):
    authentication_classes = []
    permission_classes = []
    
    def get(self, request, format=None):
        #case_counts = Cases.objects.group_by(endtime__year__in=case_years).count() # replace these with actual SQL by next wednesday
        case_counts = Cases.objects.raw('SELECT HREADY_ID, WEEK(STARTTIME) as week, count(*) as week_counts FROM CASES GROUP BY WEEK(STARTTIME)')
        week_cases = {}
        for case in case_counts:
            week_cases[case.week] = case.week_counts

        case_hours = Cases.objects.raw('SELECT HREADY_ID, HOUR(STARTTIME) as hour, count(*) as hour_counts FROM CASES GROUP BY HOUR(STARTTIME)')
        hours = {}
        for item in case_hours:
            hours[item.hour] = item.hour_counts

        data = {
            "wlabels": week_cases.keys(),
            "hlabels": hours.keys(),
            "wvalues": week_cases.values(),
            "hvalues": hours.values()
        }
        
        
        return Response(data) 

HReady-Django/HReady/templates/charts/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Django + Charts.js</title>

    {% include 'charts/base/css.html' %}
    {% include 'charts/base/bootstrap_defaults.html' %}
  </head>
  <body>
    <div class='container'>
    {% block content %}
    {% endblock content %}
    </div>
    {% include 'charts/base/js.html' %}
    <script>
    $(document).ready(function(){
      {% block jquery %}{% endblock %}
    })
    </script>
  </body>
</html>

HReady-Django/HReady/templates/charts/charts.html
{% extends 'system/dashboard.html' %}

<script>
{% block jquery %}
var endpoint = '/charts/data/'
var wvalues = []
var wlabels = []
var hlabels = []
var hvalues = []

$.ajax({
    method: "GET",
    url: endpoint,
    success: function(data){
        wlabels = data.wlabels
        wvalues = data.wvalues
        hlabels = data.hlabels
        hvalues = data.hvalues
        setChart()
    },
    error: function(error_data){
        console.log("error")
        console.log(error_data)
    }
})

function setChart(){
    var ctx = document.getElementById("myChart").getContext("2d");
    var ctx2 = document.getElementById("myChart2");
    var gradientStroke = ctx.createLinearGradient(500, 0, 100, 0);
    gradientStroke.addColorStop(0, "yellow");
    gradientStroke.addColorStop(0.5, "green");
    gradientStroke.addColorStop(1, "blue");
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: hlabels,
        datasets: [{
            label: 'Hourly Case Breakdown',
            data: hvalues,
            backgroundColor: gradientStroke,
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

    var myChart = new Chart(ctx2, {
    type: 'line',
    data: {
        labels: wlabels,
        datasets: [{
            label: 'Weekly Case Aggregate',
            data: wvalues,
            //backgroundColor: [
            //    'rgba(255, 99, 132, 0.2)',
            //    'rgba(54, 162, 235, 0.2)',
            //    'rgba(255, 206, 86, 0.2)',
            //    'rgba(75, 192, 192, 0.2)',
            //    'rgba(153, 102, 255, 0.2)',
            //    'rgba(255, 159, 64, 0.2)'
            //],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            pointBorderColor: gradientStroke,
            pointBackgroundColor: "black",
            borderWidth: 1
        }]
    },
    //options: {
    //    scales: {
    //        yAxes: [{
    //            ticks: {
    //                beginAtZero:true
    //            }
    //        }]
    //    }
    //}
});
}
// var ctx = document.getElementById("myChart");



{% endblock %}
</script>

{% block content %}
<div class='row'>
    <div class='col-sm-12' url-endpoint='{% url "charts:chart-data" %}'>
        <h1></h1>
        <div class='col-sm-6'>
            <canvas id="myChart" width="400" height="400"></canvas>
        </div>
        <div class='col-sm-6'>
            <canvas id="myChart2" width="400" height="400"></canvas>
        </div>


    </div>
</div>
{% endblock content %}