HReady-Django/HReady/HReady/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views as user_views
from tracking import views as tracking_views

from .views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='landing'),
    path('home/', user_views.home, name='home'),
    path('users/', include('users.urls', namespace='users')),
    path('system/', include('system.urls', namespace='system')),    
    path('charts/', include('charts.urls', namespace='charts')),
    path('tracking/', include('tracking.urls', namespace='tracking'))
]

HReady-Django/HReady/charts/urls.py
from django.shortcuts import redirect, render
from django.urls import path, include

from .views import ChartData, HomeView

app_name = 'charts'

urlpatterns = [
    path('', HomeView.as_view(), name='chart'),
    path('data/', ChartData.as_view(), name='chart-data')
]

HReady-Django/HReady/notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

HReady-Django/HReady/system/urls.py
from django.shortcuts import redirect, render
from django.urls import path, include
from .views import *

app_name = 'system'

urlpatterns = [
    path('', include([
        path('subjects/', SubjectListView.as_view(), name='subjects'),
        path('subjects/create', SubjectCreateView.as_view(), name='subject-create'),
        path('subjects/id/<int:pk>/', SubjectDetailView.as_view(), name='subject-detail'),
        path('subjects/update/<int:pk>/', SubjectUpdateView.as_view(), name='subject-update'),
        path('cases/', CaseListView.as_view(), name='dashboard'),
        path('cases/create', CaseCreateView.as_view(), name='case_create'),
        path('cases/id/<int:pk>/', CaseDetailView.as_view(), name='case-detail'),
        path('cases/update/<int:pk>/', CaseUpdateView.as_view(), name='case-update')
    ]))
]

HReady-Django/HReady/users/urls.py
from django.shortcuts import redirect, render
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', user_views.SignUpView.as_view(), name='signup'),
    path('signup/first_responder', user_views.FirstResponderSignupView.as_view(), name='firstresponder_signup'),
    path('signup/hospital', user_views.HospitalAdminSignupView.as_view(), name='hospitaladmin_signup')
]

HReady-Django/HReady/system/models.py
from django.db import models
from django.urls import reverse

from users.models import Hospital_Admin, First_Responder

# Create your models here.

# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.

class Staff(models.Model):
    id = models.IntegerField(db_column='ID', primary_key=True)  # Field name made lowercase.
    occupation = models.CharField(db_column='OCCUPATION', max_length=15)  # Field name made lowercase.
    details = models.CharField(db_column='DETAILS', max_length=30, blank=True, null=True)  # Field name made lowercase.
    provider_id = models.IntegerField(db_column='PROVIDER_ID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'STAFF'

class HospitalGeneralInfo(models.Model):
    provider_id = models.AutoField(db_column='PROVIDER_ID', primary_key=True)  # Field name made lowercase.
    hospital_name = models.CharField(db_column='HOSPITAL_NAME', max_length=255, blank=True, null=True)  # Field name made lowercase.
    address = models.CharField(db_column='ADDRESS', max_length=255, blank=True, null=True)  # Field name made lowercase.
    city = models.CharField(db_column='CITY', max_length=255, blank=True, null=True)  # Field name made lowercase.
    state = models.CharField(db_column='STATE', max_length=2, blank=True, null=True)  # Field name made lowercase.
    zip_code = models.CharField(db_column='ZIP_CODE', max_length=5, blank=True, null=True)  # Field name made lowercase.
    county_name = models.CharField(db_column='COUNTY', max_length=255, blank=True, null=True)  # Field name made lowercase.
    phone_number = models.IntegerField(db_column='PHONE_NUM', blank=True, null=True)  # Field name made lowercase.
    hospital_type = models.CharField(db_column='TYPE', max_length=255, blank=True, null=True)  # Field name made lowercase.
    emergency_services = models.CharField(db_column='EMERGENCY_SERVICES', max_length=3, blank=True, null=True)  # Field name made lowercase.
    #hospital_admin = models.OneToOneField(Hospital_Admin, blank=True, null=True, on_delete=models.SET_NULL)
    #hospital_overall_rating = models.IntegerField(db_column='Hospital_overall_rating', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'PROVIDERS'


class Subjects(models.Model):
    patient_id = models.AutoField(db_column='PATIENT_ID', primary_key=True)  # Field name made lowercase.
    patient_name = models.CharField(db_column='PATIENT_NAME', max_length=255)
    gender = models.CharField(db_column='GENDER', max_length=6, blank=True, null=True)  # Field name made lowercase.
    dob = models.DateField(db_column='DOB', blank=True, null=True)  # Field name made lowercase.
    dod = models.DateField(db_column='DOD', blank=True, null=True)  # Field name made lowercase.
    dod_hosp = models.DateField(db_column='DOD_HOSP', blank=True, null=True)  # Field name made lowercase.
    dead = models.IntegerField(db_column='DEAD', blank=True, null=True)  # Field name made lowercase.
    insurance = models.CharField(db_column='INSURANCE', max_length=255, blank=True, null=True)  # Field name made lowercase.
    blood_type = models.CharField(db_column='BLOOD_TYPE', max_length=3, blank=True, null=True)  # Field name made lowercase.

    def get_absolute_url(self):
        return reverse('system:subject-detail', kwargs={'pk': self.pk})

    class Meta:
        managed = True
        db_table = 'SUBJECTS'

class Cases(models.Model):
    hready_id = models.AutoField(db_column='HREADY_ID', primary_key=True)
    hadm_id = models.IntegerField(db_column='HADM_ID')  # Field name made lowercase.
    subject = models.ForeignKey(Subjects, db_column='SUBJECT_ID', on_delete=models.CASCADE)  # Field name made lowercase.
    provider = models.ForeignKey(HospitalGeneralInfo, db_column='PROVIDER_ID', null=True, on_delete=models.SET_NULL)
    starttime = models.DateTimeField(db_column='STARTTIME', auto_now_add=True)  # Field name made lowercase.
    endtime = models.DateTimeField(db_column='ENDTIME', blank=True, null=True)  # Field name made lowercase.
    closed = models.IntegerField(db_column='CLOSED', default=0)  # Field name made lowercase.
    expire_flag = models.IntegerField(db_column='EXPIRE_FLAG', default=0)  # Field name made lowercase.
    updated = models.DateTimeField(db_column='LAST_UPDATE', auto_now=True)  # Field name made lowercase.

    def get_absolute_url(self):
        return reverse('case-detail', kwargs={'pk': self.pk})

    class Meta:
        managed = True
        db_table = 'CASES'

class CaseEvents(models.Model):
    hready_id = models.ForeignKey(Cases, db_column='HREADY_ID', on_delete=models.CASCADE)  # Field name made lowercase.
    hadm_id = models.IntegerField(db_column='HADM_ID')  # Field name made lowercase.
    event_num = models.IntegerField(db_column='EVENT_NUM')  # Field name made lowercase.
    cgid = models.IntegerField(db_column='CGID')  # Field name made lowercase.
    description = models.CharField(db_column='DESCRIPTION', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'CASE_EVENTS'

HReady-Django/HReady/system/forms.py
from django import forms
from django.db import transaction

from .models import Cases

class CaseUpdateForm(forms.ModelForm):
    class Meta:
        model = Cases
        fields = ['hadm_id', 'provider', 'subject', 'expire_flag']

HReady-Django/HReady/system/views.py
from django.shortcuts import render
from django.views.generic import (ListView, TemplateView, DetailView, UpdateView, CreateView, View)
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .models import Staff, Subjects, HospitalGeneralInfo, Cases

from .forms import CaseUpdateForm

# Create your views here.
decorators = [login_required]


######################################################
###################Case Views#########################
######################################################

class CaseListView(ListView):
    """ Dashboard for hospital administrator """
    model = Cases
    template_name = 'system/case_list.html'
    paginate_by = 40

class CaseDetailView(DetailView):
    """ Individual view for a case """
    queryset = Cases.objects.order_by('-updated')
    template_name = 'system/case_detail.html'



class CaseUpdateView(UpdateView):
    model = Cases
    template_name = 'system/case_detail.html'
    

class CaseCreateView(CreateView):
    model = Cases
    fields = ['subject_id']
    template_name = 'system/case_create.html'


######################################################
###################Subject Views######################
######################################################

class SubjectListView(ListView):
    queryset = Subjects.objects.filter(dob__year__gte=1982, dob__year__lte=2018).order_by('patient_id')
    template_name = 'system/subject_list.html'
    paginate_by = 100
    context_object_name = 'patients'


class SubjectDetailView(DetailView):
    model = Subjects
    template_name = 'system/subject_detail.html'

class SubjectCreateView(CreateView):
    model = Subjects
    fields = ['gender', 'dob','dead', 'insurance', 'blood_type']
    template_name = 'subject_create.html'

class SubjectUpdateView(UpdateView):
    model = Subjects
    template_name = 'system/subject_update.html'
    form_class = CaseUpdateForm

######################################################
###################CaseEvent Views####################
######################################################

HReady-Django/HReady/templates/system/case_create.html
{% extends 'base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

HReady-Django/HReady/templates/system/case_detail.html
{% extends 'system/dashboard.html' %}


{% block content %}
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      {% for field_name in field_names %}
      <tr>
	<th>{% get_field_label object field_name %}</th>
      </tr>
      {% endfor %}
    </thead>
    <tbody>
      {% for field_name in field_names %}
      <tr>
	<td> {% get_field_value object field_name %}</td>
      </tr>
      {% endfor %}
    </tbody>
    </table>
</div>
{% endblock %}

HReady-Django/HReady/templates/system/case_update.html
{% extends 'base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}

HReady-Django/HReady/templates/system/cases_list.html
{% extends 'system/dashboard.html' %}

{% block content %}
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>Admission ID</th>
	<th>Case ID</th>
        <th>Case Creation Date</th>
        <th>Last Update</th>
        <th>Alive</th>
      </tr>
    </thead>
    <tbody>
      {% for case in object_list %}
      <tr>
        <td><a href="{% url 'system:case-update' case.hready_id %}">{{case.hadm_id}}</a></td>
        <td>case id:<a href="{% url 'system:subject-detail' case.subject.patient_id %}">{{case.subject.patient_id}}</a></td>
        <td>{{case.starttime}}</td>
        <td>{{case.updated|default:"N/A"}}</td>
	{% if case.expire_flag == 1 %}
        <td>no</td>
	{% else %}
	<td>yes</td>
	{% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="page-item disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
  {% endif %}

{% endblock %}

HReady-Django/HReady/templates/system/dashboard.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>HReady!</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">

    <!-- Jquery things -->
    {% include 'charts/base/css.html' %}
    {% include 'charts/base/bootstrap_defaults.html' %}
    
    {% include 'charts/base/js.html' %}


    <script>
      $(document).ready(function(){
        {% block jquery %}{% endblock %}
      })
    </script>
  </head>


  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'system:dashboard' %}">Hready</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="{% url 'users:logout' %}">Sign out</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only"></span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'system:subjects' %}">
                  <span data-feather="shopping-cart"></span>
                  Subjects
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'system:dashboard' %}">
                  <span data-feather="bar-chart-2"></span>
                  Cases
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span></span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'charts:chart' %}">
                  <span data-feather="file-text"></span>
                  Analytics
                </a>
              </li>
            </ul>
          </div>
        </nav>
	
	
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
           <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            {% block h1 %} {% endblock h1 %}
           </div>
          <div class="container">
            {% block canvas %}
            {% endblock canvas %}
          </div>
	  {% block content %} 
	  {% endblock content %}
        </main>
      </div>
    </div>
  </body>


</html>

HReady-Django/HReady/templates/system/subject_detail.html
{% extends 'system/dashboard.html' %}


{% block content %}
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      {% for field_name in field_names %}
      <tr>
	<th>{% get_field_label object field_name %}</th>
      </tr>
      {% endfor %}
    </thead>
    <tbody>
      {% for field_name in field_names %}
      <tr>
	<td> {% get_field_value object field_name %}</td>
      </tr>
      {% endfor %}
    </tbody>
    </table>
</div>
{% endblock %}

HReady-Django/HReady/templates/system/subject_list.html
{% extends 'system/dashboard.html' %}

{% block content %}
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>Gender</th>
        <th>Date of Birth</th>
        <th>Insurance Type</th>
        <th>Blood Type</th>
      </tr>
    </thead>
    <tbody>
      {% for patient in object_list %}
      <tr>
        <td><a href="{% url 'system:subject-update' patient.patient_id %}" style="color:red">ID: {{patient.patient_id}} </a></td>
        <td>{{patient.gender}}</td>
        {% if not patient.dob %}
          <td>Unknown</td>
        {% else %}
          <td>{{patient.dob|default:"Unknown"}}</td>
        {% endif %}
        <td>{{patient.insurance|default:"Unknown"}}</td>
        <td>{{patient.blood_type|default:"Unknown"}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="page-item disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
  {% endif %}
{% endblock %}

HReady-Django/HReady/templates/system/subject_update.html
{% extends 'base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}