HReady-Django/HReady/HReady/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views as user_views
from tracking import views as tracking_views

from .views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='landing'),
    path('home/', user_views.home, name='home'),
    path('users/', include('users.urls', namespace='users')),
    path('system/', include('system.urls', namespace='system')),    
    path('charts/', include('charts.urls', namespace='charts')),
    path('tracking/', include('tracking.urls', namespace='tracking'))
]

HReady-Django/HReady/notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

HReady-Django/HReady/users/urls.py
from django.shortcuts import redirect, render
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', user_views.SignUpView.as_view(), name='signup'),
    path('signup/first_responder', user_views.FirstResponderSignupView.as_view(), name='firstresponder_signup'),
    path('signup/hospital', user_views.HospitalAdminSignupView.as_view(), name='hospitaladmin_signup')
]

HReady-Django/HReady/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    {% block links %}{% endblock %}
  </head>
  <style>
    html,
    body{
      background-color: #009980;
    }
  </style>
  <body>

    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#"> HReady </a>
      <!-- <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> -->
      <div>
        <ul class="navbar-nav px-3">
          {% if user.is_authenticated %}
          <li class="nav-item text-nowrap">
            <a class="nav-link" href="{% url 'users:logout' %}">Sign out</a>
          </li>
          {% else %}
          <li>
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </li>
          <!-- <li>
            <a class="nav-link" href="{% url 'users:signup' %}">C-reate an account</a>
          </li> -->
          {% endif %}
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="container">
      {% block content %}

      {% endblock %}

    </main><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/bootstrap.js' %}">
  </body>
</html>

HReady-Django/HReady/templates/landing.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Cover Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand"></h3>
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="{% url 'landing' %}">Home</a>
            <a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a>
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </nav>
        </div>
      </header>

      <main role="main" class="inner cover">
        <h1 class="cover-heading">Welcome to HReady</h1>
        <p class="lead">HReady seeks to create a simple relationship between medical first responders, medical facilities and their administrators</p>
        <p class="lead">
          <a href="#" class="btn btn-lg btn-secondary">Learn more</a>
        </p>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
        </div>
      </footer>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>